server:
  port: 8083

spring:
  application:
    name: ms-solicitudes
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tpi-backend
          jwk-set-uri: http://keycloak:8080/realms/tpi-backend/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:tpi_backend_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

springdoc:
  api-docs.enabled: true
  swagger-ui.path: /swagger-ui.html

logging:
  level:
    com.backend.tpi.ms_solicitudes: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  file:
    name: logs/ms-solicitudes.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB

app:
  calculos:
    base-url: http://ms-gestion-calculos:8081
  rutas:
    base-url: http://ms-rutas-transportistas:8082

keycloak:
  admin:
    server-url: http://keycloak:8080
    realm: master
    client-id: admin-cli
    client-secret:
    username: admin
    password: admin123
